### ISSUE TITLE
关于glove.pkl的疑问

### ISSUE THREAD

**Issue by MModerato** [2014gaokao/pedestrian-attribute-recognition-with-GCN#12]
Hi！
    因为之前没有接触过词向量，对代码中这一部分有点疑问想向您请教一下：
    代码中用torch.nn.Embedding生成了glove.pkl文件，我的理解是用torch.nn.Embedding得到了一个初始的词向量矩阵，这时候词向量之间的语义信息应该并不丰富，经过模型训练之后才能得到具有联系的词向量才对，但是在demo代码中我看到加载了GCN模型的权重，而词向量依然是从之前保存的glove.pkl中读取的，是我的理解错误了吗？我总觉得nn.Embedding中的权重也会得到训练？
    希望能得到您的答复，谢谢！

**Comment by 2014gaokao** [comment]
对，其实应该对词向量进行训练再生成glove.pkl的，这样会包含语义信息，但是我也没接触过词向量，我这里只是单纯为了让标签变成数字好输入模型

**Comment by MModerato** [comment]
谢谢您这么及时的回复！
