### ISSUE TITLE
Model weights download

### ISSUE THREAD

**Issue by kHarshit** [2014gaokao/pedestrian-attribute-recognition-with-GCN#4]
Hi, Thanks for sharing your work. Can you please upload the model weights file on dropbox or drive? As I don't understand Chinese, I'm having a hard time downloading the it.

**Comment by Mantha-Cheung** [comment]
https://drive.google.com/open?id=1olDm1EedHpAzROerI21-Gi2IE0alWADR

**Comment by kHarshit** [comment]
Thank you @Mantha-Cheung

**Comment by kHarshit** [comment]
Hi @Mantha-Cheung, can you please look at https://github.com/2014gaokao/pedestrian-attribute-recognition-with-GCN/issues/6

Is the error related to model itself?
